name: Update YouTube Music Now Playing

on:
  schedule:
    - cron: "0 */1 * * *" 
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: YouTube Music Readme
        uses: asheeshh/ytm-readme@v1.1.2
        with:
          CHANNEL_ID: "UCeyqc16ASwbFldXnZAZU_Mg" 
          BACKGROUND_COLOR: "#0d1117"
          TITLE_COLOR: "#bc8cff"
          TEXT_COLOR: "#8b949e"
