name: Generate YouTube Music Widget

on:
  schedule:
    - cron: "0 */2 * * *" 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: generate-youtube-music-widget
        uses: daeun503/profile-music-widget@v1
        with:
          playlist_id: "PLPLWXKh-npBB966FhYDCgFB6ZNM7W0aiO&si=DpW-LYUjRtM42zLA"
          theme: "dark.svg"
          is_gif_bg: false

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: update youtube music widget" && git push
