name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Pacman Graph
        uses: maurodesouza/github-contribution-graph-action@v2
        with:
          github_user_name: syharipf
          output_branch: pacman-output
          output_ext: svg
